services:
  notion-auto-archive:
    image: notion-auto-archive:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output:/home/workspace/notion-auto-archive/output
    env_file:
      - .env
  pdf-reader:
    image: pdf-reader:latest
    ports:
      - 8081:80
    volumes:
      - ./output:/home/workspace/pdf-reader/output
