services:
  notion-auto-archive:
    image: notion-auto-archive:latest
    build: docker/.
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
