FROM nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl git wget unzip software-properties-common libgl1-mesa-dev && \
    nano libtext-unidecode-perl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install latexml dependencies
RUN apt-get update -qq && apt-get install -qy texlive-full
RUN apt-get update -qq && apt-get install -qy texlive-latex-recommended \
    libarchive-zip-perl libfile-which-perl libimage-size-perl  \
    libio-string-perl libjson-xs-perl libtext-unidecode-perl \
    libparse-recdescent-perl liburi-perl libuuid-tiny-perl libwww-perl \
    libxml2 libxml-libxml-perl libxslt1.1 libxml-libxslt-perl  \
    imagemagick libimage-magick-perl perl-doc build-essential \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/latexml
WORKDIR /usr/src/latexml
ENV LATEXML_COMMIT=7fe716a7e8d67958e4005512c0c6f2acf838781a
RUN curl -L https://github.com/brucemiller/LaTeXML/tarball/$LATEXML_COMMIT | tar --strip-components 1 -zxf - \
    && perl Makefile.PL \
    && make \
    && make install

# install node
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get update && apt-get install -y nodejs

# install python3.9
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-get update && apt install -y python3.9 python3.9-distutils python3.9-venv
RUN ln -s /usr/bin/python3.9 /usr/bin/python
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py

RUN mkdir /home/workspace
WORKDIR /home/workspace

RUN git clone https://github.com/discus0434/notion-auto-archive.git

# install python packages
RUN cd /home/workspace/notion-auto-archive && \
    python -m venv venv && \
    source venv/bin/activate && \
    pip install -r requirements.txt

# install node packages
RUN cd /home/workspace/notion-auto-archive/js && \
    npm install

RUN cd /home/workspace/notion-auto-archive && \
    chmod +x start_watcher.sh
