CANDIDATE_LABELS = {
    "JavaScript": "JavaScript",
    "Python": "Python",
    "React": "React",
    "TypeScript": "TypeScript",
    "ポエム": "engineer poem",
    "AWS": "AWS",
    "機械学習": "machine learning",
    "個人開発": "self development",
    "フロントエンド": "web frontend",
    "CSS": "CSS",
    "Rust": "Rust",
    "GitHub": "GitHub",
    "Rails": "Ruby on Rails",
    "Flutter": "Flutter",
    "Docker": "Docker",
    "HTML": "HTML",
    "Ruby": "Ruby",
    "Go": "Go",
    "iOS": "iOS",
    "Git": "Git",
    "AI": "AI",
    "翻訳": "translation",
    "Vue.js": "Vue.js",
    "PHP": "PHP",
    "Next.js": "Next.js",
    "データ分析": "data analysis",
    "VSCode": "VSCode",
    "競技プログラミング": "competitive programming",
    "next.js": "next.js",
    "Linux": "Linux",
    "C#": "C#",
    "Security": "Security",
    "Unity": "Unity",
    "Android": "Android",
    "DeepLearning": "DeepLearning",
    "Web": "Web",
    "Design": "Design",
    "Firebase": "Firebase",
    "Node.js": "Node.js",
    "Laravel": "Laravel",
    "Vim": "Vim",
    "GCP": "GCP",
    "データサイエンス": "data science",
    "AtCoder": "AtCoder",
    "新人教育": "newbie education",
    "SQL": "SQL",
    "Swift": "Swift",
    "Neovim": "Neovim",
    "Markdown": "Markdown",
    "Dart": "Dart",
    "Bash": "Bash",
    "DDD": "DDD",
    "ShellScript": "ShellScript",
    "Terraform": "Terraform",
    "統計学": "統計学",
    "リファクタリング": "refactoring",
    "要件定義": "requirements definition",
    "API": "API",
    "PostgreSQL": "PostgreSQL",
    "shell": "shell",
    "GraphQL": "GraphQL",
    "Slack": "Slack",
    "SwiftUI": "SwiftUI",
    "frontend": "frontend",
    "Deno": "Deno",
    "ChatGPT": "ChatGPT",
    "UNIX": "UNIX",
    "DB": "Database",
    "Windows": "Windows",
    "ゲーム制作": "game development",
    "アプリ開発": "app development",
    "ディープラーニング": "deep learning",
    "Qiita": "Qiita",
    "Google Cloud": "Google Cloud",
    "MySQL": "MySQL",
    "チーム開発": "team development",
    "jQuery": "jQuery",
    "OSS": "OSS",
    "Google": "Google",
    "C++": "C++",
    "UX": "UX",
    "C": "C",
    "VS Code": "VS Code",
    "luup": "luup",
    "Kaggle": "Kaggle",
    "自然言語処理": "natural language processing",
    "チームビルディング": "team building",
    "フリーランス": "freelance",
    "POSIX": "POSIX",
    "プロジェクト管理": "project management",
    "Firestore": "Firestore",
    "Java": "Java",
    "画像認識": "image recognition",
    "SPA": "SPA",
    "scikit-learn": "scikit-learn",
    "PyTorch": "PyTorch",
    "Kotlin": "Kotlin",
    "wasm": "wasm",
    "Kubernetes": "Kubernetes",
    "Snowflake": "Snowflake",
    "dbt": "dbt",
    "GitHubActions": "GitHubActions",
    "正規表現": "regular expression",
    "デザインパターン": "design pattern",
    "ECMAScript": "ECMAScript",
    "Nuxt": "Nuxt",
    "npm": "npm",
    "Chrome": "Chrome",
    "GAS": "GAS",
    "Jest": "Jest",
    "深層学習": "深層学習",
    "botter": "botter",
    "IoT": "IoT",
    "Julia": "Julia",
    "GitHub Actions": "GitHub Actions",
    "openai": "openai",
    "Elixir": "Elixir",
    "SaaS": "SaaS",
    "docker-compose": "docker-compose",
    "dockerfile": "dockerfile",
    "pandas": "pandas",
    "画像生成": "image generation",
    "WSL": "WSL",
    "GitLab": "GitLab",
    "ドメイン駆動設計": "domain-driven design",
    "ゲーム": "ゲーム",
    "プロジェクトマネジメント": "project management",
    "chrome-extension": "chrome-extension",
    "Network": "Network",
    "Webアプリケーション": "Web application",
    "YouTube": "YouTube",
    "勉強": "勉強",
    "Notion": "Notion",
    "テクニカルライティング": "technical writing",
    "アジャイル": "agile",
    "agile": "agile",
    "仮想通貨": "cryptocurrency",
    "CircleCI": "CircleCI",
    "Storybook": "Storybook",
    "VisualStudioCode": "VisualStudioCode",
    "macOS": "macOS",
    "StableDiffusion": "StableDiffusion",
    "react-hooks": "react-hooks",
    "lightgbm": "lightgbm",
    "開発プロセス": "development process",
    "Heroku": "Heroku",
    "deno": "deno",
    "アンチパターン": "anti-pattern",
    "Mac": "Mac",
    "colaboratory": "colaboratory",
    "インフラ": "infrastructure",
    "データベース": "database",
    "GoogleAppsScript": "GoogleAppsScript",
    "リーダブルコード": "readable code",
    "MachineLearning": "MachineLearning",
    "RaspberryPi": "RaspberryPi",
    ".NET": ".NET",
    "UniRx": "UniRx",
    "SSH": "SSH",
    "Cloud": "Cloud",
    "Angular": "Angular",
    "統計": "statistics",
    "WebAPI": "WebAPI",
    "ECS": "ECS",
    "CloudRun": "CloudRun",
    "Prisma": "Prisma",
    "UI/UX": "UI/UX",
    "Raspberry Pi": "Raspberry Pi",
    "kaggle": "kaggle",
    "Haskell": "Haskell",
    "Godot": "Godot",
    "Poetry": "Poetry",
    "Terminal": "Terminal",
    "スクレイピング": "web scraping",
    "最適化": "optimization",
    "WSL2": "WSL2",
    "画像処理": "image processing",
    "DeepL": "DeepL",
    "OpenAPI": "OpenAPI",
    "Database": "Database",
    "animation": "animation",
    "scss": "scss",
    "gcp": "gcp",
    "WebRTC": "WebRTC",
    "Linuxコマンド": "Linux commands",
    "NestJS": "NestJS",
    "mermaid": "mermaid",
    "Svelte": "Svelte",
    "vpc": "vpc",
    "linebot": "linebot",
    "gRPC": "gRPC",
    "Draw.io": "Draw.io",
    "git-flow": "git-flow",
    "REST-API": "REST-API",
    "Recoil": "Recoil",
    "webpack": "webpack",
    "Apache": "Apache",
    "GIS": "GIS",
    "SVG": "SVG",
    "devops": "devops",
    "ヒューリスティック": "heuristic",
    "NLP": "NLP",
    "フレームワーク": "framework",
    "Django": "Django",
    "M1": "M1",
    "コーディング規約": "coding convention",
    "font": "font",
    "Ubuntu": "Ubuntu",
    "人工知能": "artificial intelligence",
    "SNS": "SNS",
    "マイクロサービス": "microservice",
}
